name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f408d4b326a976fd7a74ae8944080851ec735cf3941df4701f33df414762bfb5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
