name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79085961bf8261fc7852392312df21534105dfff0f691f5920e2dad9995f8ec0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
