name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcab1e2561610fccca69d619741973b9d444435a4798c265f4f53eb1be7b7db3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
