name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73740fe58e2fb2fc14e03f5e35e15a40167451c1d634baa50671966352581a76"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
