name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a303b86dc4c965be60554f717a4b540f36de07890811cd922edad6b628b618a1"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
