name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b405ff2da193ae18a345feaca033f21519a5e6f4e3b1213aa806f4508c444178"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
