name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d3b1e2e1fd90118d857bcdd835e98bf57879f0784e21de7a5ffccc6024fca89"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
