name = "Serenity Modpack"
author = "luigistyle, Michaili K, others"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c9a85a98692af5a1e737d3be2cd9b17b8e1f73e3d3b140b3ab0fa1c103a5bde"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
