player = {}

[global]
        #Should use commands to build using this mod.
        useCommands = false
        #Should allow players to use this mod.
        allowUseMod = true
        #Should allow players to break blocks using this mod.
        allowBreakBlocks = false
        #Should allow players to place blocks using this mod.
        allowPlaceBlocks = true
        #The maximum distance a player can reach when building using this mod. 
        #Range: 0 ~ 32767
        maxReachDistance = 128
        #The maximum box volume a player can break at once when building using this mod.. 
        #Range: 0 ~ 2147483647
        maxBoxVolumePerBreak = 16384
        #The maximum box volume a player can place at once  when building using this mod. 
        #Range: 0 ~ 2147483647
        maxBoxVolumePerPlace = 16384
        #The maximum box side length a player can break at once when building using this mod. 
        #Range: 0 ~ 32767
        maxBoxSideLengthPerBreak = 1024
        #The maximum box side length a player can place at once when building using this mod. 
        #Range: 0 ~ 32767
        maxBoxSideLengthPerPlace = 1024
        #The list of items that players are allowed to use when building using this mod. 
        #If the whitelist is empty, all items are allowed. 
        #If the whitelist is not empty, only the items in the whitelist are allowed. 
        #The value must be a list of item resource locations like ["minecraft:stone", "minecraft:dirt"].
        whitelistedItems = []
        #The list of items that players are not allowed to use when building using this mod. 
        #If the blacklist is empty, no items are not allowed. 
        #If an item exists both in the blacklist and the whitelist, it will not be allowed. 
        #The value must be a list of item resource locations like ["minecraft:stone", "minecraft:dirt"].
        blacklistedItems = []